function [Hmin] = PlotDualGpThreeRounds(rho1,phi2)
tic


[sigma,theta,~] = GenAssemblagesThreeRounds(rho1,phi2);
r = length(theta);

for j=1:r
    sigmatemp{1} = sigma{j,1};
    sigmatemp{2} = sigma{j,2};
    sigmatemp{3} = sigma{j,3};
   
   
[Ftemp,violationtemp] = ...
    GenerateFunctionalThreeRounds(sigmatemp);

[Pg(j)] = DualGPThreeRounds(sigmatemp,Ftemp,violationtemp);
Hmin(j) = -log2(Pg(j));
end

subplot(1,2,1); plot(theta/pi,Pg,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for three rounds');...
hold on;

subplot(1,2,2); plot(theta/pi,Hmin,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for three rounds');...
hold on;
toc