function [Pg1] = PlotDualGpOneRoundNoisy

epsilon = 0.15;
[rhonoisy] = GenerateNoisyState(epsilon);
[rhoperf] = GenerateNoisyState(0);

[sigmaperf,theta,~]  = GenAssemblagesOneRound(rhoperf{1});
[sigma1,~,~]         = GenAssemblagesOneRound(rhonoisy{1});
[sigma2,~,~]     = GenAssemblagesOneRound(rhonoisy{2});
[sigma3,~,~]     = GenAssemblagesOneRound(rhonoisy{3});
[sigma4,~,~]     = GenAssemblagesOneRound(rhonoisy{4});

r = length(theta);

for j=1:r
    sigmatempperf = sigmaperf{j,1};
    
    sigmatemp1 = sigma1{j,1};
    sigmatemp2 = sigma2{j,1};
    sigmatemp3 = sigma3{j,1};
    sigmatemp4 = sigma4{j,1};
    
    [Ftempperf,violationtempperf] = ...
    GenerateFunctionalOneRound(sigmatempperf);

[Ftemp1,violationtemp1] = ...
    GenerateFunctionalOneRound(sigmatemp1);
[Ftemp2,violationtemp2] = ...
    GenerateFunctionalOneRound(sigmatemp2);
[Ftemp3,violationtemp3] = ...
    GenerateFunctionalOneRound(sigmatemp3);
[Ftemp4,violationtemp4] = ...
    GenerateFunctionalOneRound(sigmatemp4);

[Pgperf(j)] = DualGPOneRound(violationtempperf,sigmatempperf,Ftempperf);
Hminperf(j) = -log2(Pgperf(j));

[Pg1(j)] = DualGPOneRound(violationtemp1,sigmatemp1,Ftemp1);
Hmin1(j) = -log2(Pg1(j));

[Pg2(j)] = DualGPOneRound(violationtemp2,sigmatemp2,Ftemp2);
Hmin2(j) = -log2(Pg2(j));

[Pg3(j)] = DualGPOneRound(violationtemp3,sigmatemp3,Ftemp3);
Hmin3(j) = -log2(Pg3(j));

[Pg4(j)] = DualGPOneRound(violationtemp4,sigmatemp4,Ftemp4);
Hmin4(j) = -log2(Pg4(j));
end

subplot(1,2,1); plot(theta/pi,Pgperf,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for one round');...
hold on;

subplot(1,2,2); plot(theta/pi,Hminperf,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for one round');...
hold on;

subplot(1,2,1); plot(theta/pi,Pg1,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for one round');...
hold on;

subplot(1,2,2); plot(theta/pi,Hmin1,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for one round');...
hold on;

subplot(1,2,1); plot(theta/pi,Pg2,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for one round');...
hold on;

subplot(1,2,2); plot(theta/pi,Hmin2,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for one round');...
hold on;
subplot(1,2,1); plot(theta/pi,Pg3,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for one round');...
hold on;

subplot(1,2,2); plot(theta/pi,Hmin3,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for one round');...
hold on;

subplot(1,2,1); plot(theta/pi,Pg4,'linewidth',1.5); grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('Guessing Probability');...
title('Guessing Probability as a function of \theta_1 for one round');...
hold on;

subplot(1,2,2); plot(theta/pi,Hmin4,'linewidth',1.5);...
grid on;...
xlabel('\theta_1 (units of \pi)');...
ylabel('H_{min} (Number of Random Bits)');...
title('Min Entropy as a function of \theta_1 for one round');...
hold on;

 subplot(1,2,2); legend('\epsilon = 0','\epsilon = 0.15','Round 1 purification \epsilon = 0.1',...
     'Round 2 purification \epsilon = 0.02','Round 3 purification \epsilon = 0.005')



